app:
  head:
    title: 'MeDM: Mediating Image Diffusion Models for Video-to-Video Translation with Temporal Correspondence Guidance'
    meta:
    - name: 'description'
      content: 'MeDM utilizes pre-trained image Diffusion Models for video-to-video translation with consistent temporal flow. The proposed framework can render videos from scene position information, such as a normal G-buffer, or perform text-guided editing on videos captured in real-world scenarios. We employ explicit optical flows to construct a practical coding that enforces physical constraints on generated frames and mediates independent frame-wise scores. By leveraging this coding, maintaining temporal consistency in the generated videos can be framed as an optimization problem with a closed-form solution. To ensure compatibility with Stable Diffusion, we also suggest a workaround for modifying observed-space scores in latent-space Diffusion Models. Notably, MeDM does not require fine-tuning or test-time optimization of the Diffusion Models.'
    - name: "google-site-verification"
      content: "I9VHWgYS9g3o8RUJ7ryB1hPoIcN9YK1bX1Ds7_uDIYE"
  meta:
    title: 'MeDM: Mediating Image Diffusion Models for Video-to-Video Translation with Temporal Correspondence Guidance'
    ogTitle: 'MeDM: Mediating Image Diffusion Models for Video-to-Video Translation with Temporal Correspondence Guidance'
    description: 'MeDM utilizes pre-trained image Diffusion Models for video-to-video translation with consistent temporal flow. The proposed framework can render videos from scene position information, such as a normal G-buffer, or perform text-guided editing on videos captured in real-world scenarios. We employ explicit optical flows to construct a practical coding that enforces physical constraints on generated frames and mediates independent frame-wise scores. By leveraging this coding, maintaining temporal consistency in the generated videos can be framed as an optimization problem with a closed-form solution. To ensure compatibility with Stable Diffusion, we also suggest a workaround for modifying observed-space scores in latent-space Diffusion Models. Notably, MeDM does not require fine-tuning or test-time optimization of the Diffusion Models.'
    ogDescription: 'MeDM utilizes pre-trained image Diffusion Models for video-to-video translation with consistent temporal flow. The proposed framework can render videos from scene position information, such as a normal G-buffer, or perform text-guided editing on videos captured in real-world scenarios. We employ explicit optical flows to construct a practical coding that enforces physical constraints on generated frames and mediates independent frame-wise scores. By leveraging this coding, maintaining temporal consistency in the generated videos can be framed as an optimization problem with a closed-form solution. To ensure compatibility with Stable Diffusion, we also suggest a workaround for modifying observed-space scores in latent-space Diffusion Models. Notably, MeDM does not require fine-tuning or test-time optimization of the Diffusion Models.'
    ogImage: 'https://medm2023.github.io/images/system-diagram.jpg'
    twitterCard: 'summary_large_image'


header:
  title: 'MeDM<div>Mediating Image Diffusion Models for Video-to-Video Translation with Temporal Correspondence Guidance</div>'
  venue: 'AAAI 2024'
  authors:
  - text: 'Ernie Chu'
    homepage: 'https://ernestchu.github.io'
    mark: ''
  - text: 'Tzuhsuan Huang'
    homepage: ''
    mark: ''
  - text: 'Shuo-Yen Lin'
    homepage: ''
    mark: ''
  - text: 'Jun-Cheng Chen'
    homepage: 'https://www.citi.sinica.edu.tw/pages/pullpull'
    mark: ''

  affiliations:
  - text: 'Research Center for Information Technology Innovation, Academia Sinica'
    mark: ''

  links:
  - text: 'Paper'
    url: 'https://doi.org/10.1609/aaai.v38i2.27899'
    icon:
    - 'ai'
    - 'ai-doi'
  - text: 'Poster'
    url: '/medm-poster.pdf'
    icon:
    - 'fa-regular'
    - 'fa-file-pdf'
  - text: 'arXiv'
    url: 'https://arxiv.org/abs/2308.10079'
    icon:
    - 'ai'
    - 'ai-arxiv'
  - text: 'Code'
    url: 'https://github.com/aiiu-lab/MeDM'
    icon:
    - 'fa-brands'
    - 'fa-github'
  - text: 'Citation'
    url: 'https://github.com/aiiu-lab/MeDM?tab=readme-ov-file#citation'
    icon:
    - 'fa-brands'
    - 'fa-github'


